### ISSUE TITLE
#US06 Como usuario cliente quiero tener la posibilidad de modificar datos de registración.

### ISSUE THREAD

**Issue by LeonardoEC** [enbalde-ispc/enbalde-ispc#24]
Hipotéticamente, el cliente cambia de domicilio, cuenta de mail, o teléfono de contacto, por lo que requiere modificar sus datos de registro.

**Comment by fmdcba** [comment]
![image](https://github.com/enbalde-ispc/enbalde-ispc/assets/95236196/1bb2ed3b-d462-44a3-8b2f-a2a35d03976f)
