### ISSUE TITLE
#US11 Como usuario cliente, cuando quiero ver la información detallada de un producto puedo hacer clic en su imagen o nombre para acceder a su seccion individual.

### ISSUE THREAD

**Issue by LeonardoEC** [enbalde-ispc/enbalde-ispc#29]
Como usuario cliente, cuando quiero ver la información detallada de un producto, puedo hacer clic en su imagen o nombre para acceder a su página individual.

**Comment by fmdcba** [comment]
-[x] #69 
-[x] #70 
-[x] #189
