### ISSUE TITLE
#US15 Como usuario cliente, cuando quiero realizar el pago de mi carrito de compras puedo hacer clic en el botón "Pagar" para ingresar mis datos de pago y completar la transacción.

### ISSUE THREAD

**Issue by LeonardoEC** [enbalde-ispc/enbalde-ispc#33]
Como usuario cliente, cuando quiero realizar el pago de mi carrito de compras puedo hacer clic en el botón "Pagar" para ingresar mis datos de pago y completar la transacción.

**Comment by fmdcba** [comment]
- [x] #169
