### ISSUE TITLE
#US19 Como usuario cliente, una vez que finalice todos los pasos de la compra, quiero ver una notificación confirmando que la misma fue exitosa.

### ISSUE THREAD

**Issue by LeonardoEC** [enbalde-ispc/enbalde-ispc#37]
Como usuario cliente, una vez que finalice todos los pasos de la compra, quiero ver una notificación confirmando que la misma fue exitosa.

**Comment by fmdcba** [comment]
![sell](https://github.com/enbalde-ispc/enbalde-ispc/assets/95236196/e196379b-8886-4a9c-98c2-f12a1eb56e88)
