### ISSUE TITLE
#TK01 Diseñar una pantalla de registración

### ISSUE THREAD

**Issue by LeonardoEC** [enbalde-ispc/enbalde-ispc#40]

**Comment by rpgrca** [comment]
@LuciaL152 Podés subir la imagen del diseño acá y linkear a Figma y cerrar la tarea.

**Comment by LuciaL152** [comment]
LINK DE FIGMA: https://www.figma.com/design/qhiGB8moj0Nut4prykpgBw/En-balde?node-id=0%3A1&t=gGk0BKgtaRDrFjRL-1 


![signup](https://github.com/enbalde-ispc/enbalde-ispc/assets/106400404/535cdca4-ab81-43ba-952a-d2fabb469b9c)
