### ISSUE TITLE
#TK02 Diseñar la pantalla de login

### ISSUE THREAD

**Issue by LeonardoEC** [enbalde-ispc/enbalde-ispc#41]

**Comment by rpgrca** [comment]
@LuciaL152 Podés subir la imagen del diseño acá y linkear a Figma y cerrar la tarea.

**Comment by LuciaL152** [comment]
LINK DE FIGMA: https://www.figma.com/design/qhiGB8moj0Nut4prykpgBw/En-balde?node-id=0%3A1&t=gGk0BKgtaRDrFjRL-1 

![LOGIN](https://github.com/enbalde-ispc/enbalde-ispc/assets/106400404/1b49321b-e773-46a4-93cd-47f67b973842)
